alias: Turn off lights at sunrise
trigger:
  platform: sun
  event: sunrise
action:
  - service: light.turn_off
    entity_id: group.lampen_woonkamer
  - service: light.turn_off
    entity_id: group.lampen_achtertuin
  - service: light.turn_off
    entitiy_id: group.lammpen_slaapkamer
