homeassistant:
  name: Klapper
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  temperature_unit: C
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor: !include_dir_list sensors

# Nest thermostat
nest:
  username: !secret nest_username
  password: !secret nest_password

climate:
  platform: nest

device_tracker: !include device_tracker.yaml

ifttt:
  key: !secret ifttt_key

zone: !include zones.yaml

group: !include groups.yaml

automation: !include_dir_list automation
