alias: On sunset turn on thermostat
trigger:
  platform: state
  entity_id: sun.sun
  from: 'above_horizon'
  to: 'below_horizon'
action:
  - service: climate.set_away_mode
    entity_id: climate.living_room
    data:
      away_mode: 'False'
