alias: On sunsise turn off thermostat when nobody is at home
trigger:
  platform: state
  entity_id: sun.sun
  from: 'below_horizon'
  to: 'above_horizon'
condition:
  condition: state
  entity_id: group.all_devices
  state: 'not_home'
action:
  - service: climate.set_away_mode
    entity_id: climate.living_room
    data:
      away_mode: 'True'
  - service: ifttt.trigger
    data: {"event":"thermostat_mode", "value1":"OFF"}
