alias: Send notification when jojanneke arrives at home
trigger:
  platform: state
  entity_id: device_tracker.android4be461b69234839b
  from: 'not_home'
  to: 'home'
action:
  service: ifttt.trigger
  data: {"event":"someone_arrived_home", "value1":"Jojanneke"}
