alias: Turn on lights at sunset
trigger:
  platform: sun
  event: sunset
  offset: "-00:30:00"
action:
  service: homeassistant.turn_on
  entity_id:
    - light.achterlamp
    - light.voorlamp
    - light.buitenlamp
