alias: Turn on lights at sunset
trigger:
  platform: sun
  event: sunset
action:
  - service: light.turn_on
    entity_id: group.lampen_woonkamer
    data:
      brightness: 180
  - service: light.turn_on
    entity_id: group.lampen_achtertuin
    data:
      brightness: 65
