alias: Send notification when martijn leaves home
trigger:
  platform: state
  entity_id: device_tracker.pi_martijn
  from: 'home'
  to: 'not_home'
action:
  service: ifttt.trigger
  data: {"event":"someone_left_home", "value1":"Martijn"}
