alias: Send notification when martijn arrives at home
trigger:
  platform: state
  entity_id: device_tracker.pi_martijn
  from: 'not_home'
  to: 'home'
action:
  service: ifttt.trigger
  data: {"event":"someone_arrived_home", "value1":"Martijn"}
