alias: Thermostat on when jojanneke leaves work
trigger:
    platform: zone
    entity_id: device_tracker.pi_jojanneke
    zone: zone.her_work
    # Event is either enter or leave
    event: leave
action:
  - service: climate.set_away_mode
    entity_id: climate.living_room
    data:
      away_mode: 'False'
  - service: ifttt.trigger
    data: {"event":"thermostat_mode", "value1":"ON"}
