alias: Thermostat on when jojanneke arrives home
trigger:
  platform: state
  entity_id: device_tracker.pi_jojanneke
  from: 'not_home'
  to: 'home'
action:
  - service: climate.set_away_mode
    entity_id: climate.living_room
    data:
      away_mode: 'False'
  - service: ifttt.trigger
    data: {"event":"thermostat_mode", "value1":"ON"}
